### ISSUE TITLE
Transponder decoder and valid PT Id's

### ISSUE THREAD

**Issue by EdwardDimaguila** [slacker87/CoreIR#1]
Hi do you have any plans on making the decoder?

on your reddit post you said that 1111111 up to 9XXXXXX PT ID could be used, i believe that the decoder would only read ID's from 2097152 to 9999999.

Sorry if i posted here im new to git.

**Comment by RaceFPV** [comment]
Good catch! Yes i plan on designing an open source receiver as well as further cleaning up the transponder codebase (like removing the required arduino library)
